version: '3.8'
services:
  identity-server:
    image: dapper-labs-identity-server:latest
    command: sh -c './wait-for.sh 172.16.240.24:5432 -t 300 -- ./identity-server-runner.sh'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dapper-labs-identity-server
    tty: true
    ports:
      - '8080:8080'
    networks:
      identity_net:
        ipv4_address: 172.16.240.2
    depends_on:
      - postgres
  
networks:
  identity_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.240.0/24"
